#!/bin/bash
#
#       /etc/init.d/jmeter-server
#
# Author: Isaac Smitley
#
# jmeter-server   Runs the JMeter Remote Server
#
# chkconfig: 2345 79 19
# description: Runs JMeter tests issued by a different server.
#
#
# processname: jmeter-server
# pidfile: /var/run/jmeter-server.pid
### BEGIN INIT INFO
# Provides: jmeter-server
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: JMeter Remote Server
# Description:       JMeter Remote Server runs JMeter tests issued from a remote server.
#
### END INIT INFO

# Source function library.
. /etc/init.d/functions
# This script will start up the jmeter server as it resides in /opt/jmeter/bin/jmeter-server

# Program name
JPATH=/usr/bin/jmeter-server

start() {
echo -n "Starting Jmeter Server :”

daemon $JPATH &
RETVAL=$?
return $RETVAL
}

stop() {
echo -n "Shutting down : ”
ps fauwx | grep jmeter-server | grep -v vi | grep -v grep | awk {'print $2'} | xargs kill
return
}

case "$1" in
start)
start
;;
stop)
stop
;;
status)

;;
restart)
stop
start
;;
reload)

echo ""Usage:  {start|stop|status”
exit 1
;;
esac
exit $?